openapi: "3.0.0"
info:
  title: goremock
  description: An API moch for *oreore server.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
components:
  schemas:
    user:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        accountName:
          type: string
paths:
  /v1/users:
    get:
      description: "Return all users"
      responses:
        200:
          description: "A list of users"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schema/user"
  /v1/user/{accountName}:
    get:
      description: "Return {accountName} user's description"
      responses:
        200:
          description: "A {accountName} user's object"
          content:
            application/json:
              schema:
                $ref: "#/components/schema/user"
