/*
 * goremock
 *
 * An API moch for *oreore server.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// V1UserAccountNameGet - 
func V1UserAccountNameGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// V1UsersGet - 
func V1UsersGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
