/*
 * goremock
 *
 * An API moch for *oreore server.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type User struct {

	Id int32 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	AccountName string `json:"accountName,omitempty"`
}
